### ISSUE TITLE
win10环境运行提示错误

### ISSUE THREAD

**Issue by piaohailin** [tabalt/gracehttp#1]
C:\Go\thrsrc\src\github.com\tabalt\gracehttp\server.go:156: undefined: syscall.SIGUSR2
C:\Go\thrsrc\src\github.com\tabalt\gracehttp\server.go:174: undefined: syscall.SIGUSR2
C:\Go\thrsrc\src\github.com\tabalt\gracehttp\server.go:218: undefined: syscall.ForkExec

**Comment by tabalt** [comment]
这个确实没有考虑windows环境。。
