### ISSUE TITLE
关于该包平滑重启的疑问请教

### ISSUE THREAD

**Issue by pathbox** [tabalt/gracehttp#10]
你好， 最近我用了你的这个包做了测试，得到这样测试结果：

对于修改配置文件，平滑重启可以读取新的配置文件，或类似的全局变量数据

而修改程序代码，重新编译的二进制程序，是无法使用的。fork的新进程的代码还是使用原有的

请问是这样吗？

但我看到 
```
fork, err := syscall.ForkExec(os.Args[0], os.Args, execSpec)
```
os.Args[0] 就是程序二进制文件， 理论上fork exec 执行的会是这个新的程序二进制文件

**Comment by tabalt** [comment]
重新编译的二进制文件也会更新的，但是注意需要覆盖原来的二进制文件

**Comment by pathbox** [comment]
@tabalt 谢谢 我再试一下
