### ISSUE TITLE
windows 环境下编译提示undefined syscall.SIGHUP...

### ISSUE THREAD

**Issue by birdycn** [tabalt/gracehttp#11]
RT

**Comment by hellojukay** [comment]
@birdycn 涉及到 fork 相关的操作 ，本项目并不能夸平台运行 , 但是可以在 所以在 Windows 上交叉编译通过。
`syscall.SIGHUP`　属于 Linux 平台的　API， 需要指定 `GOOS=linux` 环境环境变。
```shell
GOOS=linux GOARCH=amd64 go build
```

**Comment by tabalt** [comment]
楼上正解~
