### ISSUE TITLE
你好，我用demo测试时遇到一个问题

### ISSUE THREAD

**Issue by 18913672165** [tabalt/gracehttp#3]
go run 执行的程序, kill -SIGUSR2 pid 正常重启只有一次，编译后的./执行的就可以多次重启，为什么啊

**Comment by tabalt** [comment]
go run实际上是编译了一个临时文件到/tmp 目录下，第一次发送重启信号时这个临时文件是存在的，重启后临时文件会被go run删掉，所以之后发信号重启时可执行文件就不存在了。
