### ISSUE TITLE
如何处理升级问题?

### ISSUE THREAD

**Issue by howmp** [tabalt/gracehttp#4]
* 通常情况下重启说明仍然是同样的可执行文件，所以通过fork来解决平滑重启
* 但如果牵扯到可执行文件变化(代码变化重新编译)就无法fork平滑升级了

**Comment by tabalt** [comment]
重新编译的二进制文件覆盖原来的文件，再发送USR2信号给运行中的进程就是升级了

**Comment by howmp** [comment]
谢谢解答 @tabalt
