### ISSUE TITLE
file := os.NewFile(3, "") 是什么操作

### ISSUE THREAD

**Issue by hellojukay** [tabalt/gracehttp#5]
这里的常量 3 是什么含义啊

**Comment by tabalt** [comment]
父进程启动子进程的时候 将输入、输出、错误、监听端口等4个fd传过来了，这个3是第4个fd，也就是父进程监听端口的fd
https://github.com/tabalt/gracehttp/blob/0f446cd42fc62f1bce9a7cd4ce9d6c25761914cb/server.go#L197

**Comment by hellojukay** [comment]
恩，我看官方也是这么写的代码的，谢谢大神！
