### ISSUE TITLE
“父进程等待已有连接中未完成的请求处理完毕” 这部分代码好像没有看到

### ISSUE THREAD

**Issue by ntting** [tabalt/gracehttp#8]
您好，在网上拜读了您的文章 https://segmentfault.com/a/1190000004445975 ，看到做热重启的做法，但是文章中提到的第三点，在代码里没找到，第三点能请教下要怎么实现吗？

**Comment by tabalt** [comment]
https://github.com/tabalt/gracehttp/blob/master/server.go#L104
https://github.com/tabalt/gracehttp/blob/master/server.go#L165

srv.httpServer.Shutdown() 会等待所有请求关闭才会返回，进而执行 165行的 srv.shutdownChan <- true，进而 104行的 <-srv.shutdownChan 能取得数据 继续执行
